# Generated by Django 4.1.7 on 2023-03-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_postal', models.CharField(max_length=5)),
                ('nom', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_verbale', models.CharField(max_length=50)),
                ('participe_passe', models.CharField(max_length=50)),
                ('preterit', models.CharField(max_length=50)),
                ('traduction', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerPreterit', models.CharField(max_length=50)),
                ('answerParticipePasse', models.CharField(max_length=50)),
                ('dateIn', models.DateTimeField(auto_now_add=True)),
                ('idGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_verbs.game')),
                ('idVerb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_verbs.verb')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('lastname', models.CharField(max_length=254)),
                ('firstname', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=0)),
                ('idTown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_verbs.town')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='idPlayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_verbs.player'),
        ),
    ]
